django/conf/project_template/urls.py
from django.conf.urls.defaults import patterns, include, url

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', '{{ project_name }}.views.home', name='home'),
    # url(r'^{{ project_name }}/', include('{{ project_name }}.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
)

urls.py
from django.conf.urls.defaults import *

from django.contrib import admin
admin.autodiscover()

handler500 = 'djangotoolbox.errorviews.server_error'

urlpatterns = patterns('',
    # GAE related from test-app
    ('^_ah/warmup$', 'djangoappengine.views.warmup'),
    
    # enable admin urls
    (r'^admin/', include(admin.site.urls)),
    
    # TODO: move blog related URL's into blogengine/urls.py
    # blog - recent posts
    ('^$', 'blogengine.views.posts_recent'),
    
    # blog - edit post 
    (r'^post/edit/(?P<slug>[\w-]+)', 'blogengine.views.post_edit'),
    
    # blog - delete post 
    (r'^post/delete/(?P<slug>[\w-]+)', 'blogengine.views.post_delete_confirm'),
    (r'^post/delete-confirmed/(?P<slug>[\w-]+)', 'blogengine.views.post_delete'),
    
    # blog - view post
    (r'^post/view/(?P<slug>[\w-]+)', 'blogengine.views.post_view'),
    
    # gae bootstrap initial user
    (r'^gae-bootstrap/', 'blogengine.views.gae_bootstrap'),
)

blogengine/models.py
from django.db import models

class Post(models.Model):
    slug  = models.CharField(max_length=200)
    title = models.CharField(max_length=200)
    body = models.TextField()
    pub_date = models.DateTimeField('date published')

    def __unicode__(self):
        return self.title

templates/blog/delete_post_confirm.html
{% extends 'base.html' %}
{% block content %}
<div class="messages">
    <p>Are you sure you want to delete the following post?:-</p>
    <p>&quot;{{ post.title }}&quot;</p>
    <p><a href="{{ SITE_ROOT }}post/delete-confirmed/{{ post.slug }}">yes</a> | <a href="{{ SITE_ROOT }}">cancel</a></p>
</div>
{% endblock %}

templates/blog/delete_post_deleted.html
{% extends 'base.html' %}
{% block content %}
<div class="messages">
    <p>The post was deleted</p>
    <a href="{{ SITE_ROOT }}">OK</a>
</div>
{% endblock %}

templates/blog/edit_post.html
{% extends 'base.html' %}
{% block content %}
{% include "blog/edit_post_form.html" %}
{%  endblock %}

templates/blog/edit_post_form.html
{% if form_errors %}
<div class="messages">
    <p>The following must be corrected:-</p>
    <ul>
    {% for item in form_errors %}
       <li>{{ item }}</li>
    {% endfor %}
    </ul>
</div>
{% endif %}
{% if updated %}
<div class="messages">
    <p>The post has been saved <a href="{{SITE_ROOT}}post/view/{{ post.slug }}">view post</a>
</div>
{% endif %}
<form method="post" name="edit_snippet" class="admin-form" action="{{SITE_ROOT}}post/edit/{{ post.slug_for_form }}">
    {% csrf_token %}
    <div class="field">
        <label>Title</label>
        <input class="medium-text" type="text" name="post_title" value="{{ post.title }}" />
    </div>
    <div class="field">
        <label>Publication Date (dd/mm/yyyy)</label>
        <input class="medium-text" type="text" name="post_pub_date" value="{{ post.pub_date|date:"d/m/Y" }}" />
    </div>
    <div class="field">
        <label>Slug</label>
        <input class="medium-text" type="text" name="post_slug" value="{{ post.slug }}" />
    </div>
    <div class="field">
        <label>Text (HTML)</label>
        <textarea name="post_body">{{ post.body|safe }}</textarea>
    </div>
    <div class="field">
        <input type="submit" value="save post" />
    </div>
</form>

templates/blog/recent.html
{% extends 'base.html' %}
{% block content %}
{% if recent_posts %}
    
    {% for item in recent_posts %}
        <div class="post">
			<h2><a href="/post/view/{{ item.slug }}/">{{ item.title }}</a></h2>
			<span class="byline">Posted: {{ item.pub_date|date:"d/m/Y" }}</span>
			<div class="post-content">
			<p>{{ item.body|safe }}</p>
			{% if perms.blogengine.change_post %}
			<div class="controls">
			    <a href="{{ SITE_ROOT }}post/edit/{{ item.slug }}">edit post</a> | 
			    <a href="{{ SITE_ROOT }}post/delete/{{ item.slug }}">delete post</a>
			</div>
			{% endif %}
			</div>

		</div>
    {% endfor %}

    
{% else %}
    <p>No recent posts available.</p>
{% endif %}
{% if perms.blogengine.change_post %}
<div class="controls">
    <a href="{{ SITE_ROOT }}post/edit/NEW-POST">add new post</a>
</div>
{% endif %}
{% endblock %}

templates/blog/view.html
{% extends 'base.html' %}
{% block content %}
<div class="post">
    <h1>{{ post.title }}</h1>
    <span class="byline">Posted: {{ post.pub_date|date:"d/m/Y" }}</span>
    <div class="post-content">
        {{ post.body|safe}}
        {% if perms.blogengine.change_post %}
		<div class="controls">
		    <a href="{{ SITE_ROOT }}post/edit/{{ post.slug }}">edit post</a> | 
		    <a href="{{ SITE_ROOT }}post/delete/{{ post.slug }}">delete post</a>
		</div>
		{% endif %}
    </div>
    <a href="{{ SITE_ROOT }}">&laquo;Back to recent posts</a>
    
</div>
{% endblock %}